### ISSUE TITLE
Automake integration

### ISSUE THREAD

**Issue by 183amir** [ashkang/jcal#13]
Hi, I was wondering how can I include libjalali in my Makefile.am and/or configure.ac file.

Right now I am doing something like:

```
gahshomar_LDADD = $(GAHSHOMAR_LIBS) /usr/lib/libjalali.la
```

Is there a better way to do this?

**Comment by reith** [comment]
On Mon, 12 Jan 2015 03:24:50 -0800
Amir notifications@github.com wrote:

> Right now I am doing something like:
> 
> ```
> gahshomar_LDADD = $(GAHSHOMAR_LIBS) /usr/lib/libjalali.la
> ```

Just include libjalali for linking stage, by something like this:

```
gahshomar_LDADD = $(GAHSHOMAR_LIBS) -ljalali
```

You may want to use autoconf `AC_CHECK_LIB` macro to check libjalali
before making object files.  Put something like this in your
configure.ac:

```
AC_CHECK_LIB([jalali], [jstrftime], [], [ echo "*** ERROR: libjalali is
not functional"; exit -1])
```

**Comment by 183amir** [comment]
Thanks a million.
