### ISSUE TITLE
providing proper testcases and automake directives to install python bindings system-wide

### ISSUE THREAD

**Issue by ashkang** [ashkang/jcal#7]
At the moment, there are no proper documentations on how to use _pyjalali_ and there are no proper mechanisms to install _pyjalali_ system-wide using automake directives in Makefile.am. There should be a test kit and an example according to project policy, that should **demonstrate basic features** of the library. It should be placed alongside C code examples in test_kit directory. Perhaps, it would be better if we rename test_kit/jtime directory to something more meaningful, something like "examples".

**Comment by reith** [comment]
Sorry for late response, I didn't have accesss to internet.
There is setup script in `sources/setup.py`. You can install pyjalali
by `python setup.py install` after installing libjalali. I
don't know how to do this with autotools.

There are some doctests in source code. I'll make some samples to show
using `pyjalali.datetime` module. Other functions are just wrappers
around core libjalali functions, I'll document their signatures as HTML
files.
